apiVersion: skaffold/v4beta10
kind: Config
metadata:
  name: tickiting
build:
  artifacts:
    - image: narayanacharaya/auth
      context: auth
      docker:
        dockerfile: Dockerfile
manifests:
  rawYaml:
    - infra/k8s/*
deploy:
 kubectl: {}

